en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Vardhaman College of Engineering. All Rights Reserved. Handcrafted With ‚ù§ in Hyderabad. Maintained by Yayin AI Lab, Designed from [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "IPR Cell"
  description: "Site Description"
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###

  ### example menu showing children ###
  menu:
    main:
      - identifier: "about"
        name: "About"
        url: "/example-page/"
        weight: 1
      - identifier: "child-1"
        name: "About Us"
        url: "/example-page/"
        weight: 1
        post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
        parent: "about"
      - identifier: "child-2"
        name: "Policies"
        url: "/policies/"
        weight: 2
        post: "Aenean commodo ligula get dolor. Aenean massa."
        parent: "about"
      - identifier: "child-3"
        name: "Programs"
        url: "/programs/"
        weight: 3
        post: "Nulla consequat massa quis enim. Donec pede justo."
        parent: "about"
      - identifier: "ip"
        name: "IP"
        url: "/programs/"
        weight: 2
      - identifier: "ip-1"
        name: "IP COMPENDIUM"
        url: "/ipcompendium/"
        weight: 1
        post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
        parent: "ip"
      - identifier: "ip-2"
        name: "IP BLOGGER"
        url: "/ipblogger/"
        weight: 2
        post: "Nulla consequat massa quis enim. Donec pede justo."
        parent: "ip"

      - identifier: "Teck"
        name: "Technologies basket"
        url: "/technologies/"
        weight: 4
      - identifier: "startup"
        name: "startup"
        url: "/blog/"
        weight: 5
      - identifier: "start-1"
        name: "Startup weekly digest"
        url: "/startup-weekly/"
        weight: 2
        post: "Nulla consequat massa quis enim. Donec pede justo."
        parent: "startup"
      - identifier: "FAQ"
        name: "FAQ"
        url: "/faq/"
        weight: 5
      - identifier: "contact"
        name: "Contact us"
        url: "/contact/"
        weight: 7
